version: "3.8"

services:
  db:
    image: postgres:15
    container_name: rust_postgres
    restart: always
    environment:
      POSTGRES_USER: rust_user
      POSTGRES_PASSWORD: rust_password
      POSTGRES_DB: rust_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
